//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMF.Protheus_HRP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TMF.Protheus_HRP.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desconsiderado o conceito de adiantamento de PLR..
        /// </summary>
        public static string AdiantamentoPLRDesconsiderado {
            get {
                return ResourceManager.GetString("AdiantamentoPLRDesconsiderado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código não pode ser nulo..
        /// </summary>
        public static string CodigoNulo {
            get {
                return ResourceManager.GetString("CodigoNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A empresa não pode ser nula..
        /// </summary>
        public static string EmpresaNula {
            get {
                return ResourceManager.GetString("EmpresaNula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha de autenticação: usuário ou senha inválido..
        /// </summary>
        public static string ErroAutenticacao {
            get {
                return ResourceManager.GetString("ErroAutenticacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A filial não pode ser nula..
        /// </summary>
        public static string FilialNula {
            get {
                return ResourceManager.GetString("FilialNula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionário não encontrado..
        /// </summary>
        public static string FuncionarioNaoEncontrado {
            get {
                return ResourceManager.GetString("FuncionarioNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O período deve ser informado..
        /// </summary>
        public static string PeriodoNaoInformado {
            get {
                return ResourceManager.GetString("PeriodoNaoInformado", resourceCulture);
            }
        }
    }
}
